import {Dimensions, StyleSheet} from 'react-native';
const {height, width} = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {
    height: height / 5,
  },
  inputViewContainer1: {
    justifyContent: 'space-evenly',
    width: width,
    height: height / 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: '10%',
    // backgroundColor: 'red',
  },
  backicon: {height: 30, width: 30},
  leftinputIcon: {
    height: height / 30,
    width: width / 20,
    alignSelf: 'center',
  },
  input: {
    width: '70%',
    marginVertical: '1%',
    marginHorizontal: '4%',
  },
  inputView1: {
    width: width / 1.4,
    height: height / 18,
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
  },
  inputViewContainer2: {
    flexDirection: 'row',
    width: width / 1.129,
    alignSelf: 'flex-end',
    justifyContent: 'space-evenly',
  },
  inputView2: {
    width: width / 1.4,
    height: height / 18,
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
  },
  buttonStyle: {
    backgroundColor: 'aqua',
    width: '30%',
    alignSelf: 'center',
    marginTop: '15%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  modalView: {backgroundColor: 'white', flex: 1, width: '100%'},
  modalInputView: {
    marginTop: '14%',
    marginHorizontal: '3%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
  },
  modalBackButton: {left: '20%'},
  modalBackButtonIcon: {height: 24, width: 24},
  modalLocationButtonView: {
    height: '20%',
    marginTop: '10%',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  locationButtonStyles: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'aqua',
    height: 50,
    paddingHorizontal: '3%',
    borderRadius: 5,
  },
  locationButtonIcongps: {height: 24, width: 24, tintColor: 'blue'},
  buttonText: {fontSize: 18, paddingHorizontal: 10},
  locationButtonIcongpspin: {height: 24, width: 24},
});
