export const localStrings = {
  placeholder: 'Search Here',
  mode: 'DRIVING',
  Standard: 'standard',
  Min: 'min',
  KM: 'km',
  mapType: 'Map Type',
  satellite: 'satellite',
  terrain: 'terrain',
  DistanceQuote: 'Fastest route now due to traffic conditions',
  currentLocation: 'Your Location',
  chooseMap: 'Choose on Map',
  enterSource: 'enter Source location',
  enterDestination: 'enter destination location',
  showRoute: 'Show Route',
};
